name: "Build"

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Set up Deno"
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: "Check with Deno"
        run: |
          deno check

      - name: "Test with Deno"
        run: |
          deno task test
